from src.agent.parser import parse_tool_calls, strip_attribution


def test_strip_attribution() -> None:
    text = "hello\n\n---\n*[Generated by x]*"
    assert strip_attribution(text) == "hello"


def test_parse_tool_calls_from_object() -> None:
    payload = (
        '{"tool_calls":[{"id":"a","name":"web_search","arguments":{"query":"python"}}]}'
    )
    calls = parse_tool_calls(payload)
    assert len(calls) == 1
    assert calls[0].name == "web_search"
    assert calls[0].arguments["query"] == "python"


def test_parse_tool_calls_from_fenced_json() -> None:
    payload = (
        '```json\n[{"name":"memory_write","arguments":{"note":"Remember this"}}]\n```'
    )
    calls = parse_tool_calls(payload)
    assert len(calls) == 1
    assert calls[0].name == "memory_write"


def test_parse_tool_calls_returns_empty_for_non_json() -> None:
    calls = parse_tool_calls("Here is a normal assistant response.")
    assert calls == []
