"""
Tool-call parser for local-model text outputs.
"""

from __future__ import annotations

import json
import re
from typing import Any

from .types import ToolCall

_JSON_BLOCK_PATTERN = re.compile(
    r"```(?:json)?\s*(\{[\s\S]*?\}|\[[\s\S]*?\])\s*```", re.IGNORECASE
)


def strip_attribution(content: str) -> str:
    """Remove orchestrator model attribution if present."""
    marker = "\n\n---\n*[Generated by "
    if marker in content:
        return content.split(marker, maxsplit=1)[0].strip()
    return content.strip()


def _extract_candidate_payloads(text: str) -> list[str]:
    candidates: list[str] = []

    for match in _JSON_BLOCK_PATTERN.finditer(text):
        candidates.append(match.group(1).strip())

    stripped = text.strip()
    if stripped.startswith("{") and stripped.endswith("}"):
        candidates.append(stripped)
    if stripped.startswith("[") and stripped.endswith("]"):
        candidates.append(stripped)

    for marker in ('{"tool_calls"', '{"tool_call"', "[{"):
        idx = text.find(marker)
        if idx >= 0:
            candidates.append(text[idx:].strip())

    # Keep order, drop exact duplicates.
    deduped: list[str] = []
    seen: set[str] = set()
    for candidate in candidates:
        if candidate not in seen:
            deduped.append(candidate)
            seen.add(candidate)
    return deduped


def _coerce_call(raw_call: dict[str, Any], fallback_index: int) -> ToolCall | None:
    name = raw_call.get("name")
    args = raw_call.get("arguments", {})
    if not isinstance(name, str) or not name.strip():
        return None
    if not isinstance(args, dict):
        return None

    call_id = raw_call.get("id")
    if not isinstance(call_id, str) or not call_id.strip():
        call_id = f"call-{fallback_index}"

    return ToolCall(
        id=call_id.strip(),
        name=name.strip(),
        arguments=args,
    )


def _parse_payload(payload: Any) -> list[ToolCall]:
    raw_calls: list[dict[str, Any]] = []

    if isinstance(payload, dict):
        if isinstance(payload.get("tool_calls"), list):
            for item in payload["tool_calls"]:
                if isinstance(item, dict):
                    raw_calls.append(item)
        elif isinstance(payload.get("tool_call"), dict):
            raw_calls.append(payload["tool_call"])
        elif isinstance(payload.get("name"), str):
            raw_calls.append(payload)
    elif isinstance(payload, list):
        for item in payload:
            if isinstance(item, dict) and isinstance(item.get("name"), str):
                raw_calls.append(item)

    parsed: list[ToolCall] = []
    for index, raw_call in enumerate(raw_calls, start=1):
        call = _coerce_call(raw_call, fallback_index=index)
        if call is not None:
            parsed.append(call)
    return parsed


def parse_tool_calls(model_output: str) -> list[ToolCall]:
    """
    Parse tool calls from model text.

    Returns an empty list if no valid tool payload is found.
    """
    cleaned = strip_attribution(model_output)
    if not cleaned:
        return []

    for candidate in _extract_candidate_payloads(cleaned):
        try:
            payload = json.loads(candidate)
        except json.JSONDecodeError:
            continue

        parsed = _parse_payload(payload)
        if parsed:
            return parsed

    return []
